### ISSUE TITLE
Re-Add Staging Cluster

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ci#27]
With the cluster upgrade, can we get staging back? I promise not to use it for dummy data for the UI ( 😂 ), rather as a live demo of the end-of-sprint deliverables and something to reference our local instances to. For UI development we are all using our local Minishift instance.

I'd like to be able to use staging to link to it from the GitHub organization or repo, or even the community site if there is a use case for that (though I'm guessing most won't have access to it, so maybe not worth it?). I welcome any thoughts on this.

Please let me know if this is in the wrong repo so I can move it.

cc @rhuss

**Comment by kahboom** [comment]
@dsimansk kindly shared this link (thanks!), which may or may not work, but may be worth a shot: https://github.com/syndesisio/syndesis-openshift-templates/tree/master/staging

**Comment by dsimansk** [comment]
I've followed the steps, and everything is up now.

Btw to the public access. Yes you're right that would require to add them to syndesisio GH org to access the cluster.
